pool:
  vmImage: 'VS2017-Win2016'

trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.4' 

- task: NuGetCommand@2
  displayName: "NuGet pack"
  inputs:
    command: pack
    packagesToPack: '**/*.nuspec'
    packDestination: $(Build.ArtifactStagingDirectory)
    versioningScheme: byEnvVar
    versionEnvVar: Build.SourceBranchName

- task: NuGetCommand@2
  displayName: "NuGet push"
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: NuGet.org
    packagesToPush: $(Build.ArtifactStagingDirectory)\**\*.nupkg