pool:
  vmImage: 'VS2017-Win2016'

trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.4' 

- task: PowerShell@2
  displayName: "Find releases without a nuget package"
  inputs:
    filePath: "scripts/FindVersions.ps1"

- task: PowerShell@2
  condition: and(succeeded(), ne(variables['versionsToPublish'], ''))
  displayName: "Download Advanced Combat Tracker versions"
  inputs:
    filePath: "scripts/Download.ps1"
    arguments: -Versions $(versionsToPublish)

- task: PowerShell@2
  condition: and(succeeded(), ne(variables['versionsToPublish'], ''))
  displayName: "Create NuGet packages"
  inputs:
    filePath: "scripts/Pack.ps1"
    arguments: -Versions $(versionsToPublish) -OutputDirectory $(Build.ArtifactStagingDirectory)

- task: NuGetCommand@2
  displayName: "NuGet push"
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: NuGet.org
    packagesToPush: $(Build.ArtifactStagingDirectory)\**\*.nupkg
