pool:
  vmImage: 'VS2017-Win2016'

name: 0.0.$(Rev:r)
steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.4' 

- task: NuGetCommand@2
  displayName: "NuGet pack"
  inputs:
    command: pack
    packagesToPack: '**/*.nuspec'
    packDestination: $(Build.ArtifactStagingDirectory)
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: "NuGet push"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: NuGet.org
    packagesToPush: $(Build.ArtifactStagingDirectory)\**\*.nupkg