pool:
  vmImage: 'VS2017-Win2016'

trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

variables:
  ActVersion: 3.4.2.262

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.4' 

- task: PowerShell@2
  displayName: "Download Advanced Combat Tracker executable"
  inputs:
    filePath: "scripts/Download.ps1"
    arguments: -Version $(ActVersion)

- task: NuGetCommand@2
  displayName: "NuGet pack"
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    command: pack
    packagesToPack: '**/*.nuspec'
    packDestination: $(Build.ArtifactStagingDirectory)
    versioningScheme: byEnvVar
    versionEnvVar: Build.SourceBranchName
    buildProperties: "ActVersion=$(ActVersion)"
    
- task: NuGetCommand@2
  displayName: "NuGet push"
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: NuGet.org
    packagesToPush: $(Build.ArtifactStagingDirectory)\**\*.nupkg